// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfIEC8OgGWF0hRD7kDSoaJsfPERmiOTHY',
    appId: '1:349525717107:web:f901b8c5f0e27c82307a06',
    messagingSenderId: '349525717107',
    projectId: 'devai-c58ae',
    authDomain: 'devai-c58ae.firebaseapp.com',
    storageBucket: 'devai-c58ae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2R-meLBmCSstxhagJ-VLc8bU6hph2538',
    appId: '1:349525717107:android:d18eebd556affafb307a06',
    messagingSenderId: '349525717107',
    projectId: 'devai-c58ae',
    storageBucket: 'devai-c58ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEjsE5Pubh3uEjjq7fo-Gr5HH_GwAyOsw',
    appId: '1:349525717107:ios:00d4e7b4dfb8d918307a06',
    messagingSenderId: '349525717107',
    projectId: 'devai-c58ae',
    storageBucket: 'devai-c58ae.firebasestorage.app',
    androidClientId: '349525717107-1b9jrh6hqeh951fplp21h7m4m9maqo7q.apps.googleusercontent.com',
    iosClientId: '349525717107-h06v728blbc97qtr4qvffbc0l14v8vtj.apps.googleusercontent.com',
    iosBundleId: 'com.devstudio.devai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfIEC8OgGWF0hRD7kDSoaJsfPERmiOTHY',
    appId: '1:349525717107:web:34fed9f49886d46f307a06',
    messagingSenderId: '349525717107',
    projectId: 'devai-c58ae',
    authDomain: 'devai-c58ae.firebaseapp.com',
    storageBucket: 'devai-c58ae.firebasestorage.app',
  );
}
